# Generated by Django 3.2.9 on 2021-12-26 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211226_2053'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrestaurantcategory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='foodrestaurantcategory',
            name='food',
        ),
        migrations.RemoveField(
            model_name='mealcategory',
            name='food',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='food_restaurant_category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='meal_category',
        ),
        migrations.AddField(
            model_name='menu',
            name='branch',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='restaurant.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='food',
            field=models.ManyToManyField(related_name='food', to='restaurant.Food'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.branchaddress'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='food_restaurant_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.foodrestaurantcategory'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_restaurant_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.foodrestaurantcategory'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.RemoveField(
            model_name='food',
            name='meal_category',
        ),
        migrations.AddField(
            model_name='food',
            name='meal_category',
            field=models.ManyToManyField(related_name='meal', to='restaurant.MealCategory'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
