# Generated by Django 3.2.9 on 2021-12-27 09:29

from django.db import migrations, models
import django.db.models.deletion
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_foodorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to=restaurant.models.Food.upload_path),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='food',
        ),
        migrations.AddField(
            model_name='menu',
            name='food',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='restaurant.food'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('سفارش', 'سفارش'), ('ثبت', 'ثبت'), ('ارسال', 'ارسال'), ('تحویل', 'تحویل')], default='not paid', max_length=10),
        ),
    ]
