# Generated by Django 3.2.9 on 2021-12-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20211227_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodOrder',
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.branchaddress'),
        ),
    ]
