# Generated by Django 3.2.9 on 2021-12-27 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20211227_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.branchaddress'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='food_restaurant_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.foodrestaurantcategory'),
        ),
    ]
