# Generated by Django 3.2.9 on 2021-12-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_branch_food_restaurant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_restaurant_category',
        ),
        migrations.AddField(
            model_name='food',
            name='food_restaurant_category',
            field=models.ManyToManyField(related_name='food_cat', to='restaurant.FoodRestaurantCategory'),
        ),
    ]
