# Generated by Django 3.2.9 on 2022-01-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_branch_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
