# Generated by Django 3.2.9 on 2022-01-05 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20220104_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuorder',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
