# Generated by Django 3.2.9 on 2022-01-05 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_menuorder_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuorder',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
