# Generated by Django 3.2.9 on 2022-01-05 20:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_alter_menuorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_rel', to='restaurant.branch'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_rel', to='restaurant.food'),
        ),
        migrations.AlterField(
            model_name='menuorder',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_rel', to='restaurant.menu'),
        ),
        migrations.AlterField(
            model_name='menuorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_rel', to='restaurant.order'),
        ),
        migrations.AlterField(
            model_name='menuorder',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_rell', to='restaurant.branch'),
        ),
    ]
