# Generated by Django 3.2.9 on 2022-01-05 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='menuorder',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
