# Generated by Django 3.2.9 on 2022-01-09 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_auto_20220106_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuorder',
            name='number',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menuorder',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
