# Generated by Django 3.2.9 on 2021-12-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
