# Generated by Django 3.2.9 on 2021-12-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_admin_customer_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'مدیر سایت', 'verbose_name_plural': 'مدیران سایت'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'مدیر رستوران', 'verbose_name_plural': 'مدیر های رستوران'},
        ),
    ]
