# Generated by Django 3.2.9 on 2021-12-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211226_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_address',
            field=models.ManyToManyField(to='accounts.UserAddress'),
        ),
    ]
