# Generated by Django 3.2.9 on 2022-01-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220101_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
