# Generated by Django 3.2.9 on 2022-01-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_useraddress_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
