# Generated by Django 3.2.9 on 2022-01-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220106_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_main',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
