# Generated by Django 3.2.9 on 2022-01-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_useraddress_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='device',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=14, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default=14, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default=14, max_length=50),
            preserve_default=False,
        ),
    ]
