# Generated by Django 3.2.9 on 2022-01-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220110_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_address',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraddress'),
            preserve_default=False,
        ),
    ]
