# Generated by Django 3.2.9 on 2022-01-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220110_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraddress'),
        ),
    ]
